# Run using docker, not a VM
sudo: false

# Cache sbt downloaded packages
cache:
  directories:
    - $HOME/.sbt

# Now the actual core of the script
language: scala

scala:
  - 2.11.12

script:
  - cd FeatureEngine-benchmark
  - sbt compile
  - sbt test
  - sbt scalastyle
